class DashboardSerializer < BaseSerializer
  set_id    :id
  set_type  :task

  attributes :id,
             :title,
             :description,
             :status,
             :completed_status,
             :workspace_id,
             :owner_id,
             :owner,
             :assignee_id,
             :assignee,
             :project_id,
             :project,
             :tasklist_id,
             :tasklist,
             :source_language_id,
             :source_language,
             :target_language_id,
             :target_language,
             :task_type_id,
             :task_type,
             :unit_id,
             :unit,
             :classification,
             :internal,
             :start_on,
             :due_on,
             :start_date,
             :due_date,
             :completed_on,
             :completed_date,
             :created_on,
             :updated_on,
             :created_date,
             :updated_date
end
