development: &default
  adapter: redis
  url: <%= ENV.fetch('REDIS_URL', 'redis://redis:6379/1') %>

test:
  <<: *default
  url: <%= ENV.fetch('REDIS_URL', "redis://redis:6379/1#{ENV['TEST_ENV_NUMBER']}") %>

staging:
  <<: *default

production:
  <<: *default
