development: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://localhost:5432/GliderPath_API_development') %>

test:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', "postgres://localhost:5432/GliderPath_API_test#{ENV['TEST_ENV_NUMBER']}") %>

staging:
  <<: *default

production:
  <<: *default
