default: &default
  application_domain: <%= ENV['APPLICATION_DOMAIN'] %>
  application_key: <%= ENV['APPLICATION_KEY'] %>
  google_key: <%= ENV['GOOGLE_KEY'] %>
  google_secret: <%= ENV['GOOGLE_SECRET'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

development:
  <<: *default
  application_key: qwerty123456789qwerty.quicktask.io
  application_domain: https://quicktask.io
  secret_key_base: abcd1234abcd

test:
  <<: *default
  application_key: qwerty123456789qwerty.quicktask.io
  application_domain: https://quicktask.io
  secret_key_base: abcd1234abcd

staging:
  <<: *default

production:
  <<: *default
