app:
  name: 'GliderPath'
  domain: quicktask.io
  default_email_address: <%= "gliderbot@#{ENV.fetch('SMTP_DOMAIN', 'quicktask.test')}" %>
  notifications_email_address: <%= "notifications@#{ENV.fetch('SMTP_DOMAIN', 'quicktask.test')}" %>

client:
  url: <%= ENV.fetch('CLIENT_URL', 'http://localhost:3000') %>

company:
  name: GliderPath Limited
  address: 71-75 Shelton Street, Covent Garden, London, WC2H 9JQ UK

links:
  blog: 'https://blog.gliderpath.com'
  facebook: 'https://www.facebook.com/GliderPath'
  home: 'https://gliderpath.com'
  support: 'mailto:support@gliderpath.com'
  twitter: 'https://twitter.com/GliderPath'
